### ISSUE TITLE
Surround `colors` properties in `tailwind.config.js` with quotes

### ISSUE THREAD

**Issue by grilledwindow** [bb-eleven/game-of-life#7]
Only keys with hyphens are surrounded with quotes, causing some visual disparity.
```JavaScript
colors: {
  'cadet-blue': '#A0A8C3',
  comet: '#636985',
}
```

**Comment by lenetan** [comment]
Assign this to me! :)

**Comment by lenetan** [comment]
And please tag topic "Hacktoberfest"

**Comment by grilledwindow** [comment]
Hi @lenetan, thanks for volunteering. Sorry for not being more clear on the requirements for this issue, it has something to do with `prettier` formatting the file.

A temporary solution I can think of would be to ignore this file for being formatted. I'll look into a more permanent solution in the future when I have the time.

Do you think you would be able to help with this?

**Comment by lenetan** [comment]
@grilledwindow Ah, I see. I have to opt out, I do not have the necessary knowledge to solve this.

**Comment by grilledwindow** [comment]
@lenetan No problem. I hope you find a project you'll be able to contribute to! :)

**Comment by grilledwindow** [comment]
Hi @lenetan, I managed to resolve this in #13. It turned out to be a simple one-liner to use [Quote Props](https://prettier.io/docs/en/options.html#quote-props) in `.prettierrc`.
